        <main>
            <a href="upload" id="upload">Dodaj zdjęcie</a>
            <form action="save_selected" method="post">
                <?php require_once 'layout/gallery.php'; ?>
                <input type="submit" name="save_selected" value="Zapisz zaznaczone">
            </form>
            <?php include_once 'layout/paging.php'; ?>
        </main>
        <?php require_once 'layout/footer.phtml'; ?>
        <script src="static/data.js"></script>
    </body>
</html>