        <main>
            <p>Jeśli nie masz konta, <a href="register">zarejestruj się.</a></p>
            <form method="post">
                <label for="login">Nazwa użytkownika:</label><br>
                <input type="text" id="login" name="login" required><br>
                <label for="password">Hasło:</label><br>
                <input type="password" id="password" name="password" required><br>
                <input type="submit" name="submit" value="Zaloguj się">
            </form>
            <?php
            if (isset($log_error)) {
                echo "<p>" . $log_error . "</p>";
                unset($log_error);
            } ?>
            
        </main>
        <?php require_once 'layout/footer.phtml'; ?>
        <script src="static/data.js"></script>
    </body>
</html>