        <main>
        <form method="post">
            <label for="email">Adres e-mail:</label><br>
            <input type="email" id="email" name="email" required><br>
            <label for="login">Login:</label><br>
            <input type="text" id="login" name="login" required><br>
            <label for="password">Hasło:</label><br>
            <input type="password" id="password" name="password" required><br>
            <label for="repeat_password">Powtórz hasło:</label><br>
            <input type="password" id="repeat_password" name="repeat_password" required><br><br>
            <input type="submit" value="Zarejestruj się">
        </form> 
        <?php
        if (isset($reg_error)) {
            echo "<p>" . $reg_error . "</p>";
            unset($reg_error);
        } ?>
        </main>
        <?php require_once 'layout/footer.phtml'; ?>
        <script src="static/data.js"></script>
    </body>
</html>