<!DOCTYPE html>
<html lang="pl">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="static/style.css">
        <link rel="icon" href="360713.png" type="image/x-icon">
        <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
        <title>Galeria</title>
    </head>
    <body>
        <header>
            <h1>ASTRONOMIA</h1>
        </header>
        <nav>
            <ul class="navbar">
                <li>
                    <div class="dropdown">
                        <a class="dd_button" href="index">Strona główna</a>
                        <svg width="16" height="16" fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16" id="IconChangeColor"> <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z" id="mainIconPathAttribute" stroke-width="2" stroke="#942192" fill="#5e0699"></path> </svg>
                    <div class="dd_content">
                        <a href="index#omnie">O mnie</a>
                        <a href="index#contact">Kontakt</a>
                    </div>
                    </div>
                </li>
                <li><a href="gwiazdy">Gwiazdy</a></li>
                <li><a href="ankieta">Ankieta</a></li>
                <li><a href="galeria">Galeria</a></li>
                <li><a href="selected_photos">Wybrane zdjęcia</a></li>
                <li><a href="login">Konto</a></li>
            </ul>
        </nav>
        <main>
            <a href="upload" id="upload">Dodaj zdjęcie</a>
            <form action="delete_selected" method="post">
                <?php
                foreach($selected_photos as $photo){
                    echo '<div class="photos_php">';
                    echo '<a href="' . $photo['watermark_path'] . '"><img src="' . $photo['thumbnail_path'] . '" alt=""/></a>';
                    echo '<p>Tytuł: ' . $photo['title'] . '</p>';
                    echo '<p>Autor: ' . $photo['author'] . '</p>';
                    echo '<input type="checkbox" name="delete_selected[]" value="' . $photo['_id'] . '">';
                    echo '</div>';
                    }
                ?>
                <input type="submit" name="delete" value="Usuń zaznaczone z zapamiętanych">
            </form>
            <?php include_once 'layout/paging.php'; ?>
        </main>
        <footer>
            <h4 id="contact">Kontakt</h4>
            <a href="mailto:oskarwisniewski2004@gmail.com">Email</a>
            <a href="tel:+48532602567">Nr telefonu</a>
            <a href="https://www.facebook.com/smart.skar.ymg">Facebook</a>
            <span>© Copyright 2023: Oskar Wiśniewski</span>
        </footer>
        <script src="static/data.js"></script>
    </body>
</html>