        <main>
            <form action="delete_selected" method="post">
                <?php
                foreach($selected_photos as $photo){
                    echo '<div class="photos_php">';
                    echo '<a href="' . $photo['watermark_path'] . '"><img src="' . $photo['thumbnail_path'] . '" alt=""/></a>';
                    echo '<p>Tytuł: ' . $photo['title'] . '</p>';
                    echo '<p>Autor: ' . $photo['author'] . '</p>';
                    echo '<input type="checkbox" name="delete_selected[]" value="' . $photo['_id'] . '">';
                    echo '</div>';
                    }
                ?>
                <input type="submit" name="delete" value="Usuń zaznaczone z zapamiętanych">
            </form>
            <?php include_once 'layout/paging.php'; ?>
        </main>
        <?php require_once 'layout/footer.phtml'; ?>
        <script src="static/data.js"></script>
    </body>
</html>