        <main>
            <form method="post" enctype="multipart/form-data">
            <label for="photo">Wybierz zdjęcie:</label>
            <input type="file" name="photo" id="photo" required>
            <br>
            <label for="title">Tytuł:</label>
            <input type="text" name="title" id="title" required>
            <br>
            <label for="author">Autor:</label>
            <input type="text" name="author" id="author" required>
            <br>
            <label for="watermark">Znak wodny:</label>
            <input type="text" name="watermark" id="watermark" required>
            <input type="hidden" name="id" value="">
            <br>
            <input type="submit" value="Prześlij zdjęcie">
            </form>
            <?php
            if (isset($error)) {
                echo "<p>" . $error . "</p>";
                unset($error);
            } ?>
        </main>
        <?php require_once 'layout/footer.phtml'; ?>
        <script src="static/data.js"></script>
    </body>
</html>