<!DOCTYPE html>
<html lang="pl">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="static/style.css">
        <link rel="icon" href="static/360713.png" type="image/x-icon">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
        <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
        <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
        <title>Astronomia</title>
    </head>
    <body>
        <header>
            <h1>ASTRONOMIA</h1>
        </header>
        <nav>
            <ul class="navbar">
                <li>
                    <div class="dropdown">
                        <a class="dd_button" href="index">Strona główna</a>
                        <svg width="16" height="16" fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16" id="IconChangeColor"> <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z" id="mainIconPathAttribute" stroke-width="2" stroke="#942192" fill="#5e0699"></path> </svg>
                    <div class="dd_content">
                        <a href="index#omnie">O mnie</a>
                        <a href="index#contact">Kontakt</a>
                    </div>
                    </div>
                </li>
                <li><a href="gwiazdy">Gwiazdy</a></li>
                <li><a href="ankieta">Ankieta</a></li>
                <li><a href="galeria">Galeria</a></li>
                <li><a href="selected_photos">Wybrane zdjęcia</a></li>
                <li><a href="login">Konto</a></li>
            </ul>
        </nav>